### ISSUE TITLE
 meta-kanto:     url: "https://github.com/eclipse-kanto/meta-kanto.git"     refspec: kirkstone

### ISSUE THREAD

**Issue by aricwang88** [eclipse-leda/meta-leda#112]
Compiling raspiberrypi 4B image failed, 
in kas/.config-kirkstone-rpi4.yaml missing:

 meta-kanto:
    url: "https://github.com/eclipse-kanto/meta-kanto.git"
    refspec: kirkstone

**Comment by stlachev** [comment]
Solved with:
`https://github.com/eclipse-leda/meta-leda/pull/114`
