### ISSUE TITLE
RAUC: use verity bundle format

### ISSUE THREAD

**Issue by jluebbe** [eclipse-leda/meta-leda#117]
The verity format should be used instead of the old plain format. The [current bundle recipe](https://github.com/eclipse-leda/meta-leda/blob/main/meta-leda-components/recipes-sdv/sdv-core/sdv-rauc-bundle.bb) doesn't set `RAUC_BUNDLE_FORMAT` so it defaults to plain.

It was introduced in 1.5 to address shortcomings in the plain format: https://rauc.readthedocs.io/en/latest/changes.html#release-1-5-released-dec-14-2020
See
https://rauc.readthedocs.io/en/latest/integration.html?highlight=verity#bundle-format-migration for details.

**Comment by mikehaller** [comment]
Thank you for letting us know, it has been fixed now.
