### ISSUE TITLE
RAUC: use more specific compatible

### ISSUE THREAD

**Issue by jluebbe** [eclipse-leda/meta-leda#118]
The [current bundle recipe](https://github.com/eclipse-leda/meta-leda/blob/main/meta-leda-components/recipes-sdv/sdv-core/sdv-rauc-bundle.bb) set `RAUC_BUNDLE_COMPATIBLE = "Eclipse Leda"` , so even bundles targeting different architectures use the same compatible. A common approach is to set different RAUC compatibles in the MACHINE files.

**Comment by mikehaller** [comment]
Thank you for letting us know, it has been fixed now.
