### ISSUE TITLE
qemu

### ISSUE THREAD

**Issue by MonsieurHBA** [eclipse-leda/meta-leda#188]
After using kas build how can I run qemu in my PC please

**Comment by vasilvas99** [comment]
Hi, for more in depth explanations you can refer the docs: https://eclipse-leda.github.io/leda/docs/
As a tl;dr, run:

```
  kas shell /path/to/kas-file.yaml -c 'runqemu slirp nographic ovmf sdv-image-all'
```

E.g., if you've just built the qemux86 leda-distro image, use:
```
kas shell kas/leda-qemux86-64.yaml -c 'runqemu slirp nographic ovmf sdv-image-all'
```

**Comment by mikehaller** [comment]
Closing due to no reply
