### ISSUE TITLE
Leda distro failing to build after the gpsd additions

### ISSUE THREAD

**Issue by vasilvas99** [eclipse-leda/meta-leda#191]
# What happened

After the GPSD PR (https://github.com/eclipse-leda/meta-leda/pull/178) was merged, Leda Distro builds that use meta-leda main now fail to build, due to one of the packages related to gpsd failing to compile.

# Error log
[error.log](https://github.com/eclipse-leda/meta-leda/files/12586388/error.log)

# Steps to reproduce

Check-out the main branch of leda-distro, setup a devcontainer/codespace as per the documentation and run
```
kas build kas/leda-qemux86-64.yaml:kas/mirrors.yaml
```

The build will fail with a similar error log as the one above.

**Comment by d-s-e** [comment]
This must be an issue with the devcontainer/codespace setup, like it is described in the documentation. I never used this, because it never worked on my system.

The build works fine on my local build container setup.

**Comment by vasilvas99** [comment]
Could you please share your build container setup (i.e. Dockerfile?). It seems that in the build runners the recipe seems to go through fine and I have a suspicion it might be related to the base container/os that's being used.

**Comment by d-s-e** [comment]
This is my setup: https://gist.github.com/d-s-e/a8d1c5cb1c60624a647a8cba8515679d

**Comment by vasilvas99** [comment]
It was specifically a codespace issue, closed with: https://github.com/eclipse-leda/leda-distro/pull/148
