### ISSUE TITLE
Typo in the default airgap container installation service directory

### ISSUE THREAD

**Issue by mikehaller** [eclipse-leda/meta-leda#193]
There is a typo in the "constainers" path, it should be "containers":

https://github.com/eclipse-leda/meta-leda/blob/06045e0b3ef8afcbde88cac06bbe57df7f1708a0/meta-leda-components/recipes-sdv/eclipse-leda/airgap-container-installer.bb#L24

**Comment by vasilvas99** [comment]
Fixed in: https://github.com/eclipse-leda/meta-leda/pull/201
