### ISSUE TITLE
nerdctl renamed to main branch

### ISSUE THREAD

**Issue by benmordaunt** [eclipse-leda/meta-leda#28]
https://github.com/eclipse-leda/meta-leda/blob/59a83923bfd700208ca0607099d76071fe61d66b/meta-leda-components/recipes-sdv/tools/nerdctl_0.20.0.bb#L5

Fetch fails due to branch rename: master -> main

**Comment by benmordaunt** [comment]
The same issue also appears in `meta-virtualization`s version.

**Comment by mikehaller** [comment]
A [patch to fix branch name of nerdctl](https://lists.yoctoproject.org/g/meta-virtualization/topic/patch_nerdctl_renamed/95065671?p=,,,20,0,0,0::recentpostdate/sticky,,,20,2,0,95065671,previd%3D1668604171849715298,nextid%3D1665207633199939885&previd=1668604171849715298&nextid=1665207633199939885) has been submitted to the meta-virtualization mailing list, we'll wait until this is merged and will remove the duplicate recipes in meta-leda.

**Comment by mikehaller** [comment]
Removed our duplicate recipe and added a temporary fix for nerdctl SRC_URI until upstream repository is merged in PR #41
